version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    expose:
      - "6380"
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "4001:4001"
    restart: always
    volumes:
      - .:/app
      - /app/users/node_modules
    env_file:
      - ./users/.env
  spotify:
    build:
      dockerfile: Dockerfile
      context: ./spotify
    container_name: spotify
    ports:
      - "4002:4002"
    restart: always
    volumes:
      - .:/app
      - /app/spotify/node_modules
    env_file:
      - ./spotify/.env
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - spotify
    ports:
      - 80:80

